- name: Install Cloud Custodian
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: otherdevopsgene-ansible-ssm
    ansible_aws_ssm_region: us-east-1
  become: yes

  tasks:
  - name: Install Cloud Custodian
    ansible.builtin.pip:
      name: 
        - c7n
        - c7n-azure
        - c7n-gcp
        - c7n-org
    become: yes
    become_user: ec2-user
