- name: Install Terraform
  hosts: all
  vars:
    ansible_connection: aws_ssm
    ansible_aws_ssm_bucket_name: otherdevopsgene-ansible-ssm
    ansible_aws_ssm_region: us-east-1
  become: yes

  roles:
    - role: andrewrothstein.terraform
